// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0X9S_Zlh-XyHU6gFZw1MHOoxSHZrNwUc',
    appId: '1:717848858371:web:318cf76e0c8c45f0aaa336',
    messagingSenderId: '717848858371',
    projectId: 'lockin-8c95f',
    authDomain: 'lockin-8c95f.firebaseapp.com',
    storageBucket: 'lockin-8c95f.firebasestorage.app',
    measurementId: 'G-34BESMYSD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHTjnAtpZJF9bBfKRv6xqIla-aPljWsQ',
    appId: '1:717848858371:android:00e404c75cf527edaaa336',
    messagingSenderId: '717848858371',
    projectId: 'lockin-8c95f',
    storageBucket: 'lockin-8c95f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlUxqmpCl-D40EoxH_Yf_U_oPUAzfJtI',
    appId: '1:717848858371:ios:312da0b083e294c1aaa336',
    messagingSenderId: '717848858371',
    projectId: 'lockin-8c95f',
    storageBucket: 'lockin-8c95f.firebasestorage.app',
    androidClientId:
        '717848858371-62mdbl17akacoq5cnfdoc12binr6pp2e.apps.googleusercontent.com',
    iosClientId:
        '717848858371-a190er2vb2jcjcb47n07v88bta2mhfmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArlUxqmpCl-D40EoxH_Yf_U_oPUAzfJtI',
    appId: '1:717848858371:ios:312da0b083e294c1aaa336',
    messagingSenderId: '717848858371',
    projectId: 'lockin-8c95f',
    storageBucket: 'lockin-8c95f.firebasestorage.app',
    androidClientId:
        '717848858371-62mdbl17akacoq5cnfdoc12binr6pp2e.apps.googleusercontent.com',
    iosClientId:
        '717848858371-a190er2vb2jcjcb47n07v88bta2mhfmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0X9S_Zlh-XyHU6gFZw1MHOoxSHZrNwUc',
    appId: '1:717848858371:web:6e38decb5fbd4818aaa336',
    messagingSenderId: '717848858371',
    projectId: 'lockin-8c95f',
    authDomain: 'lockin-8c95f.firebaseapp.com',
    storageBucket: 'lockin-8c95f.firebasestorage.app',
    measurementId: 'G-LJFW6XG2YX',
  );
}
